id: I0DC3B7C9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T22:31:21+00:00'
last_modified: '2022-06-10T04:12:41.896041+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3399
  title: ཉི་ཁྲིའི་འགྲེལ་པ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9BBB:
      image_group_id: I1KG3480
      title: Volume 1 of sher phyin stong phrag nyi shu lnga pa
      total_pages: 1562
      order: 1
      base_file: 9BBB.txt
    4AAA:
      image_group_id: I1KG3481
      title: Volume 2 of sher phyin stong phrag nyi shu lnga pa
      total_pages: 1588
      order: 2
      base_file: 4AAA.txt
    48AB:
      image_group_id: I1KG3482
      title: Volume 3 of sher phyin stong phrag nyi shu lnga pa
      total_pages: 1726
      order: 3
      base_file: 48AB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
